server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.74.135:8848 #nacos地址
    gateway:
      routes:
        - id: user-service #路由标识,必须唯一
          uri: lb://userservice #路由的目标地址
          predicates: #路由断言
            - Path=/user/** #路径断言，判断路径是否是以user开头
          filters:
            - AddRequestHeader=Truth,DaGuangGo is nb!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      globalcors:
        add-to-simple-url-handler-mapping: true #结局option请求被拦截的问题
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8090"
              - "http://www.baidu.com"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTION"
            allowedHeaders: "*" #允许在请求中携带的头信息
            allowCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期
